title: Rayity
description: A simple library for generative, photorealistic graphics
show_downloads: true
include: 
  - _build_
  - _camera_
  - _expression_
  - _material_
  - _model_
  - _options_
  - _renderer_
  - _scene_
  - _shape_
  - _viewer_